### ISSUE TITLE
Where are costs of primitives defined? 

### ISSUE THREAD

**Issue by A-Manning** [rfindler/395-2013#11]

**Comment by rfindler** [comment]
They are all assumed to be unit cost. If you want a non unit cost
primitive, one approach is to code it up and prove its cost. (We did this
for some of the numeric primitives.)

**Comment by A-Manning** [comment]
Where would I find the definitions for numeric primitives?

**Comment by dfeltey** [comment]
Several arithmetic primitives are defined in the arith/ directory https://github.com/rfindler/395-2013/tree/master/arith
